package org.qme.client.vis.tex;

import org.lwjgl.BufferUtils;
import org.lwjgl.opengl.GL32;
import org.qme.io.Logger;
import org.qme.io.Severity;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.HashMap;

/**
 * Class responsible for loading textures from files
 * @author cameron
 * @since PreB
 */
public class TextureManager {

    /**
     * Path to the texture locations
     */
    private static final String TEXTURE_RESOURCES = "/textures/";

    /**
     * Path to missing textures
     */
    private static final String MISSING_TEXTURE = "/textures/missing.png";

    /**
     * Every loaded texture - string name to ID
     */
    public static HashMap<String, Integer> textures = new HashMap<>();

    /**
     * Loads textures
     */
    public TextureManager() {
        ArrayList<String> toLoad = new ArrayList<>();
        toLoad.add("missing.png");
        toLoad.add("forest.png");
        toLoad.add("plains.png");
        toLoad.add("fertile-plains.png");
        toLoad.add("mountain.png");
        toLoad.add("ocean.png");
        toLoad.add("sea.png");
        toLoad.add("high-mountain.png");
        toLoad.add("desert.png");
        loadTextures(toLoad);
    }

    /**
     * Loads an array of textures by the file name
     * @param toLoad a list of file names to load
     */
    public static void loadTextures(ArrayList<String> toLoad) {
        for (String texture : toLoad) {
            textures.put(
                    texture,
                    loadTextureFromImage(
                            loadImageResource(
                                    TEXTURE_RESOURCES + texture
                            )
                    )
            );
        }
    }

    /**
     * Loads a opengl texture from an image
     * @param image Image file to load
     * @return Id of the loaded texture
     */
    public static int loadTextureFromImage(BufferedImage image) {

        GL32.glEnable(GL32.GL_TEXTURE_2D);

        int[] pixelBuf = new int[image.getWidth() * image.getHeight()];
        image.getRGB(0, 0, image.getWidth(), image.getHeight(), pixelBuf, 0, image.getWidth());
        ByteBuffer buf = BufferUtils.createByteBuffer(image.getWidth() * image.getHeight() * 4);

        for (int y = 0; y < image.getHeight(); y++) {
            for (int x = 0; x < image.getWidth(); x++) {

                int pixel = pixelBuf[y * image.getWidth() + x];

                // Get RGB
                buf.put((byte) ((pixel >> 16) & 0xFF));
                buf.put((byte) ((pixel >> 8) & 0xFF));
                buf.put((byte) (pixel & 0xFF));

                // Get alpha
                buf.put((byte) ((pixel >> 24) & 0xFF));

            }
        }

        buf.flip();

        // The id generated by GL
        int id = GL32.glGenTextures();

        GL32.glBindTexture(GL32.GL_TEXTURE_2D, id);

        GL32.glTexImage2D(
                GL32.GL_TEXTURE_2D, 0, GL32.GL_RGBA,
                image.getWidth(), image.getHeight(),
                0, GL32.GL_RGBA, GL32.GL_UNSIGNED_BYTE, buf
        );

        GL32.glActiveTexture(GL32.GL_TEXTURE0);

        GL32.glGenerateMipmap(GL32.GL_TEXTURE_2D);

        return id;

    }

    /**
     * Gets an image from resources
     * @param path path of the file
     * @return an image
     */
    private static BufferedImage loadImageResource(String path) {

        // If the texture doesn't exist try to load fallback texture
        if (TextureManager.class.getResource(path) == null) {
            Logger.log("Could not find texture " + path, Severity.ERROR);

            // Attempt to load fallback texture so the application can at least start

            if (TextureManager.class.getResource(MISSING_TEXTURE) == null) {
                Logger.log("Could not find fallback texture", Severity.FATAL);
                return null;
            }

            try {
                return ImageIO.read(TextureManager.class.getResource(MISSING_TEXTURE));
            } catch (IOException e) {
                Logger.log("Could not load fallback texture", Severity.FATAL);
                e.printStackTrace();
                return null;
            }

        }

        try {
            return ImageIO.read(TextureManager.class.getResource(path));
        } catch (IOException e) {
            // Some unforeseen error has occurred. Don't try to load fallback texture
            Logger.log("Could not load texture " + path, Severity.FATAL);
            e.printStackTrace();
            return null;
        }
    }

}
