package org.qme.client.vis.tex;

import org.lwjgl.BufferUtils;
import org.lwjgl.opengl.GL32;
import org.qme.io.Logger;
import org.qme.io.Severity;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.HashMap;

/**
 * Class responsible for loading textures from files
 * @author cameron
 * @since 0.3.0
 */
public class TextureManager {

    private static final String TEXTURE_RESOURCES = "/textures/";
    private static final String MISSING_TEXTURE = "/textures/missing.png";
    private static HashMap<String, Integer> textures = new HashMap<>();

    /**
     * Initialising TextureManager will load textures in the resources directory
     * Inorder to avoid loading textures twice this should only be initialised once
     */
    public TextureManager() {
        ArrayList<String> toLoad = new ArrayList<>();
        toLoad.add("missing.png");
        toLoad.add("forest.png");
        toLoad.add("plains.png");
        toLoad.add("fertile-plains.png");
        toLoad.add("mountain.png");
        toLoad.add("ocean.png");
        toLoad.add("sea.png");
        toLoad.add("high-mountain.png");
        toLoad.add("desert.png");
        for (String texture : toLoad) {
            registerTexture(texture, loadTextureFromImage(loadImageResource(TEXTURE_RESOURCES + texture)));
        }
    }

    /**
     * Registers a texture
     * @param name the name of the texture
     * @param id the id of the texture
     */
    public static void registerTexture(String name, int id) {
        if (textures.containsKey(name) || textures.containsValue(id)) {
            Logger.log("Failed to load texture " + name + " id " + id + " because a texture with the a common identifier exists.", Severity.WARNING);
            return;
        }
        Logger.log("Loaded texture: " + name, Severity.NORMAL);
        textures.put(name, id);
    }

    /**
     * Gets a texture by name
     * @param name the name of the texture
     * @return the texture id or null if the texture could not be found
     */
    public static Integer getTexture(String name) {
        return textures.getOrDefault(name, null);
    }

    /**
     * Loads a opengl texture from an image
     * @param image Image file to load
     * @return Id of the loaded texture
     */
    public static int loadTextureFromImage(BufferedImage image) {

        GL32.glEnable(GL32.GL_TEXTURE_2D);

        int height = image.getHeight();
        int width = image.getWidth();

        int area = height * width;

        int[] pixelBuf = new int[area];
        image.getRGB(0, 0, width, height, pixelBuf, 0, width);
        ByteBuffer buf = BufferUtils.createByteBuffer(area * 4);

        for (int y = 0; y < height; y++) {
            for (int x = 0; x < width; x++) {

                int pixel = pixelBuf[y * width + x];

                // Get RGB
                buf.put((byte) ((pixel >> 16) & 0xFF));
                buf.put((byte) ((pixel >> 8) & 0xFF));
                buf.put((byte) (pixel & 0xFF));

                // Get alpha
                buf.put((byte) ((pixel >> 24) & 0xFF));

            }
        }

        buf.flip();

        return loadTextureFromBuffer(buf, width, height);
    }

    /**
     * Loads texture from byte buffer
     * @param buffer the byte buffer to load
     * @return id of texture
     */
    public static int loadTextureFromBuffer(ByteBuffer buffer, int width, int height) {

        // The id generated by GL
        int id = GL32.glGenTextures();

        GL32.glBindTexture(GL32.GL_TEXTURE_2D, id);

        GL32.glTexImage2D(
                GL32.GL_TEXTURE_2D, 0, GL32.GL_RGBA,
                width, height,
                0, GL32.GL_RGBA, GL32.GL_UNSIGNED_BYTE, buffer
        );

        GL32.glActiveTexture(GL32.GL_TEXTURE0);

        GL32.glGenerateMipmap(GL32.GL_TEXTURE_2D);

        return id;
    }

    /**
     * Gets an image from resources
     * @param path path of the file
     * @return an image
     */
    private static BufferedImage loadImageResource(String path) {

        // If the texture doesn't exist try to load fallback texture
        if (TextureManager.class.getResource(path) == null) {
            Logger.log("Could not find texture " + path, Severity.ERROR);

            // Attempt to load fallback texture so the application can at least start

            if (TextureManager.class.getResource(MISSING_TEXTURE) == null) {
                Logger.log("Could not find fallback texture", Severity.FATAL);
                return null;
            }

            try {
                return ImageIO.read(TextureManager.class.getResource(MISSING_TEXTURE));
            } catch (IOException e) {
                Logger.log("Could not load fallback texture", Severity.FATAL);
                e.printStackTrace();
                return null;
            }

        }

        try {
            return ImageIO.read(TextureManager.class.getResource(path));
        } catch (IOException e) {
            // Some unforeseen error has occurred. Don't try to load fallback texture
            Logger.log("Could not load texture " + path, Severity.FATAL);
            e.printStackTrace();
            return null;
        }
    }

}
